config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tweets do
    member do
      post :like
    end
  end
  resources :users

  namespace :admin do
  	root 'dashboard#index'
	end

  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :user_id, presence: true
  validates :tweet_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_many :likes, foreign_key: 'tweet_id'
  has_many :liked_users, through: :likes, source: :user
  belongs_to :user

  mount_uploader :image, TweetImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets, dependent: :destroy

  has_many :likes, foreign_key: 'user_id'
  has_many :like_tweets, through: :likes, source: :tweet

  has_many :following_friendships, class_name: 'Friendship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :following_friendships, source: :followed

  has_many :followed_friendships, class_name: 'Friendship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :followed_friendships, source: :follower

  mount_uploader :image, AvatarUploader

  validates :tag_name, presence: true

  def admin?
    self.role == "admin"
  end

  def tag
    "@#{self.tag_name}"
  end

  def to_param
    tag_name
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin

  def index
    @tweets = Tweet.all
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def authenticate_admin
    raise ActiveRecord::RecordNotFound unless current_user.admin?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:tag_name, :image])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tweets = Tweet.all.order('created_at DESC')
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to :root
    else
      render :new
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to :root
    else
      render :edit
    end
  end

  def like
    @tweet = Tweet.find(params[:id])
    @user = current_user
    @like_tweet = @user.likes.find_by(tweet_id: @tweet.id)
    byebug
    if @like_tweet
      @like_tweet.destroy
      redirect_to tweets_path
    else
      @user.likes.create(tweet_id: @tweet.id)
      redirect_to tweets_path
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:description, :image, :remove_image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @user = current_user
    @tweets = current_user.tweets
  end

  def show
    @user = User.find_by(tag_name: params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to users_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:description, :image)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/dashboard/index.html.erb
<h1>ADMIN PAGE</h1>
<p>total Tweets: <%= @tweets.count %></p>
<p>total Users: <%= @users.count %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleTweet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      Hi, <%= current_user.email %>
      <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
      <%= link_to('修改密碼', edit_registration_path(:user)) %>
      <%= link_to('編輯個人資料', edit_user_path(current_user.id)) %>
    <% else %>
      <%= link_to('註冊', new_registration_path(:user)) %> |
      <%= link_to('登入', new_session_path(:user)) %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<div class="field">
  <%= f.label :description, "what are you thinking about?" %>
  <%= f.text_area :description %>
</div>

<div class="field">
  <%= f.label :image, "upload picture" %>
  <%= f.file_field :image %>
  <% if f.object.image? %>
    <%= image_tag f.object.image.url %>
    <%= f.label :remove_image %>
    <%= f.check_box :remove_image %>
  <% end %>
</div>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "post" %>
<% end %>

app/views/tweets/index.html.erb
<p><%= link_to 'say somthing!', new_tweet_path %></p>

<% @tweets.each do |tweet| %>
  <h2><%= link_to tweet.user.tag, user_path(tweet.user) %> </h2>
  <p><%= tweet.description %> </p>
  <% if tweet.image? %>
    <p><%= image_tag(tweet.image.url, height: '150', width: '150') %></p>
  <% end %>
  <% if current_user.like_tweets.exists?(tweet.id) %>
    <p><%= link_to 'unlike!', like_tweet_path(tweet), method: :post %></p>
  <% else %>
    <p><%= link_to 'like!', like_tweet_path(tweet), method: :post %></p>
  <% end %>
  <% if tweet.user_id == current_user.id %>
    <%= link_to 'edit', edit_tweet_path(tweet) %>
  <% end %>
<% end %>

app/views/tweets/new.html.erb
<%= form_for @tweet do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "post" %>
<% end %>

app/views/users/_form.html.erb
<div class="field">
  <%= f.label :description, "Say somthing about you!" %>
  <%= f.text_field :description %>
</div>

<div class="field">
  <%= f.label :image, "upload profile picture" %>
  <%= f.file_field :image %>
</div>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "update" %>
<% end %>

app/views/users/index.html.erb
<%= @user.tag %>

<% @tweets.each do |tweet| %>
  <h2><%= tweet.user.tag %></h2>
  <p><%= tweet.description %></p>
<% end %>

app/views/users/show.html.erb
<%= @user.tag %>
<%= image_tag @user.image.url %>
<%= @user.id %>